apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv-vol1
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  nfs:
    path: /nfs-share/app-data
    server: kube-master
