apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: demo
  name: demo
spec:
  ports:
  - name: 8080-80
    nodePort: 31888
    port: 8080
    protocol: TCP
    targetPort: 80
  selector:
    app: demo
  type: NodePort
status:
  loadBalancer: {}
